language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install: composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then travis_retry php vendor/bin/coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then travis_retry php vendor/bin/coveralls -v; fi
